# torch_geometric.utils

In [3]:
import torch
from torch_geometric.utils import *

## degree
根据所给索引，计算节点的度
### 参数
+ index (LongTensor)  - 边连接的节点的索引
+ num_nodes (int, optional) - 节点的数量
+ dtype(torch.dtype, optional) - 需要的返回类型

### 样例

In [33]:
a = torch.LongTensor([[2,3],[1,2],[0,3]]).t()
print(a)
headindex, tailindex = a
print("头节点:",headindex)
print("尾节点:",tailindex)
print("出度:",degree(headindex))
# tensor([1., 1., 1.])
print("入度:",degree(tailindex))
# tensor([0., 0., 1., 2.])

# 这里可以看到，出度和入度输出的维度不同，因为节点3不作为头节点，所以默认只有3个节点，如果要得到一致维度的输出，要额外传入节点个数
print("出度:",degree(headindex, num_nodes = 4))
# tensor([1., 1., 1., 0., 0.])
print("入度:",degree(tailindex, num_nodes = 4))
# tensor([0., 0., 1., 2., 0.])

tensor([[2, 1, 0],
        [3, 2, 3]])
头节点: tensor([2, 1, 0])
尾节点: tensor([3, 2, 3])
出度: tensor([1., 1., 1.])
入度: tensor([0., 0., 1., 2.])
出度: tensor([1., 1., 1., 0.])
入度: tensor([0., 0., 1., 2.])


## add_self_loops
给图添加自环
### 参数
+ edge_index (LongTensor) – 边索引.
+ edge_weight (Tensor, optional) – 边权重(default: None)
+ fill_value (float, optional) – 如果边权重为非空，则会将fill_value填给自环，作为自环的权重 (default:1)
+ num_nodes (int, optional) – 节点的数量 (default: None)

### 样例

In [37]:
a = torch.LongTensor([[2,3],[1,2],[0,3]]).t()
w = torch.FloatTensor([0.5, 0.5, 0.5])

print("无权重:",add_self_loops(a))
# (tensor([[2, 1, 0, 0, 1, 2, 3],
#         [3, 2, 3, 0, 1, 2, 3]]), None)
print("有权重:",add_self_loops(a,w,0.9))
# (tensor([[2, 1, 0, 0, 1, 2, 3],
#         [3, 2, 3, 0, 1, 2, 3]]), tensor([0.5000, 0.5000, 0.5000, 0.9000, 0.9000, 0.9000, 0.9000]))

无权重: (tensor([[2, 1, 0, 0, 1, 2, 3],
        [3, 2, 3, 0, 1, 2, 3]]), None)
有权重: (tensor([[2, 1, 0, 0, 1, 2, 3],
        [3, 2, 3, 0, 1, 2, 3]]), tensor([0.5000, 0.5000, 0.5000, 0.9000, 0.9000, 0.9000, 0.9000]))
